### ISSUE TITLE
/legacyLevels crash without legacies

### ISSUE THREAD

**Issue by lukawarren** [lukawarren/Lorien-Legacies#94]

**Comment by lukawarren** [comment]
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/14/20 7:59 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at lorien.legacies.gui.LegacyGui.func_73866_w_(LegacyGui.java:73)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017)
	at lorien.legacies.network.mesages.MessageLegacyLevelsScreen.onClientTick(MessageLegacyLevelsScreen.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_MessageLegacyLevelsScreen_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1910)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at lorien.legacies.gui.LegacyGui.func_73866_w_(LegacyGui.java:73)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1017)
	at lorien.legacies.network.mesages.MessageLegacyLevelsScreen.onClientTick(MessageLegacyLevelsScreen.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_MessageLegacyLevelsScreen_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Krypnofite'/1447, l='MpServer', x=-86.50, y=64.00, z=184.50]]
	Chunk stats: MultiplayerChunkCache: 729, 729
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-83,64,187), Chunk: (at 13,4,11 in -6,11; contains blocks -96,0,176 to -81,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 126 game time, 126 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntitySkeleton['Skeleton'/1536, l='MpServer', x=-123.50, y=23.00, z=204.50], EntityCreeper['Creeper'/1537, l='MpServer', x=-96.50, y=28.00, z=232.50], EntityZombie['Zombie'/1793, l='MpServer', x=-50.50, y=26.00, z=113.50], EntityZombie['Zombie'/1794, l='MpServer', x=-50.50, y=26.00, z=111.50], EntityEnderman['Enderman'/1795, l='MpServer', x=-48.50, y=26.00, z=113.50], EntityZombie['Zombie'/1668, l='MpServer', x=-132.50, y=25.00, z=227.50], EntityEnderman['Enderman'/1796, l='MpServer', x=-47.50, y=26.00, z=111.50], EntityZombie['Zombie'/1670, l='MpServer', x=-64.50, y=17.00, z=116.50], EntitySkeleton['Skeleton'/1543, l='MpServer', x=-25.50, y=20.00, z=261.50], EntityZombie['Zombie'/1671, l='MpServer', x=-61.50, y=17.00, z=115.50], EntitySpider['Spider'/1544, l='MpServer', x=-28.50, y=20.00, z=260.50], EntitySpider['Spider'/1546, l='MpServer', x=-30.50, y=20.00, z=259.50], EntitySpider['Spider'/1803, l='MpServer', x=-20.50, y=26.00, z=145.50], EntityZombie['Zombie'/1805, l='MpServer', x=-25.50, y=26.00, z=146.50], EntitySkeleton['Skeleton'/1808, l='MpServer', x=-33.50, y=20.00, z=257.50], EntitySkeleton['Skeleton'/1812, l='MpServer', x=-22.50, y=16.00, z=122.50], EntityZombie['Zombie'/1816, l='MpServer', x=-47.50, y=13.00, z=149.50], EntityBat['Bat'/1561, l='MpServer', x=-15.18, y=16.15, z=125.31], EntitySpider['Spider'/1818, l='MpServer', x=-30.50, y=26.00, z=142.50], EntitySkeleton['Skeleton'/1819, l='MpServer', x=-91.50, y=23.00, z=177.50], EntityCreeper['Creeper'/1820, l='MpServer', x=-163.50, y=36.00, z=172.50], EntityCreeper['Creeper'/1565, l='MpServer', x=-103.50, y=21.00, z=181.50], EntityCreeper['Creeper'/1821, l='MpServer', x=-160.50, y=36.00, z=168.50], EntityCreeper['Creeper'/1822, l='MpServer', x=-159.50, y=36.00, z=167.50], EntitySkeleton['Skeleton'/1824, l='MpServer', x=-161.50, y=36.00, z=172.50], EntityCreeper['Creeper'/1570, l='MpServer', x=-71.50, y=18.00, z=118.50], EntityZombie['Zombie'/1574, l='MpServer', x=-37.52, y=18.00, z=165.74], EntityZombie['Zombie'/1575, l='MpServer', x=-38.50, y=18.00, z=167.50], EntityPlayerSP['Krypnofite'/1447, l='MpServer', x=-86.50, y=64.00, z=184.50], EntityBat['Bat'/1704, l='MpServer', x=-136.59, y=15.07, z=212.62], EntityCreeper['Creeper'/1837, l='MpServer', x=-45.50, y=38.00, z=151.50], EntityZombie['Zombie'/1839, l='MpServer', x=-58.50, y=20.00, z=255.50], EntityBat['Bat'/1713, l='MpServer', x=-18.66, y=26.52, z=143.87], EntitySkeleton['Skeleton'/1844, l='MpServer', x=-99.50, y=12.00, z=225.50], EntityCreeper['Creeper'/1717, l='MpServer', x=-55.50, y=41.00, z=155.50], EntityCreeper['Creeper'/1591, l='MpServer', x=-28.50, y=16.00, z=115.50], EntityCreeper['Creeper'/1592, l='MpServer', x=-83.50, y=16.00, z=231.50], EntityBat['Bat'/1594, l='MpServer', x=-97.49, y=20.87, z=193.42], EntityCreeper['Creeper'/1601, l='MpServer', x=-144.45, y=20.00, z=221.32], EntitySkeleton['Skeleton'/1604, l='MpServer', x=-63.50, y=38.00, z=131.50], EntityBat['Bat'/1735, l='MpServer', x=-41.25, y=33.07, z=160.46], EntityCreeper['Creeper'/1743, l='MpServer', x=-40.50, y=36.00, z=124.50], EntitySkeleton['Skeleton'/1744, l='MpServer', x=-44.50, y=36.00, z=124.50], EntitySkeleton['Skeleton'/1745, l='MpServer', x=-42.50, y=36.00, z=124.50], EntityBat['Bat'/1617, l='MpServer', x=-126.25, y=35.07, z=107.60], EntitySkeleton['Skeleton'/1746, l='MpServer', x=-40.50, y=36.00, z=123.50], EntitySkeleton['Skeleton'/1753, l='MpServer', x=-119.50, y=25.00, z=225.50], EntityZombie['Zombie'/1755, l='MpServer', x=-43.50, y=17.00, z=164.50], EntityZombie['Zombie'/1759, l='MpServer', x=-95.50, y=15.00, z=243.50], EntityZombie['Zombie'/1632, l='MpServer', x=-47.50, y=38.00, z=146.50], EntityBat['Bat'/1638, l='MpServer', x=-50.58, y=17.04, z=114.74], EntityZombie['Zombie'/1770, l='MpServer', x=-37.50, y=32.00, z=104.50], EntitySkeleton['Skeleton'/1773, l='MpServer', x=-114.50, y=31.00, z=214.50], EntityCreeper['Creeper'/1774, l='MpServer', x=-86.50, y=19.00, z=113.50], EntitySkeleton['Skeleton'/1775, l='MpServer', x=-81.50, y=19.00, z=111.50], EntitySkeleton['Skeleton'/1776, l='MpServer', x=-80.50, y=19.00, z=114.50], EntityZombie['Zombie'/1777, l='MpServer', x=-88.50, y=19.00, z=117.50], EntitySkeleton['Skeleton'/1650, l='MpServer', x=-54.50, y=14.00, z=236.50], EntityZombie['Zombie'/1784, l='MpServer', x=-122.50, y=20.00, z=213.50], EntityBat['Bat'/1530, l='MpServer', x=-147.38, y=40.60, z=169.39], EntityBat['Bat'/1534, l='MpServer', x=-26.47, y=33.13, z=159.46], EntityCreeper['Creeper'/1662, l='MpServer', x=-118.50, y=13.00, z=183.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 251730456 bytes (240 MB) / 637534208 bytes (608 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID             | Version      | Source                             | Signature                                |
	|:--------- |:-------------- |:------------ |:---------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft      | 1.12.2       | minecraft.jar                      | None                                     |
	| UCHIJAAAA | mcp            | 9.42         | minecraft.jar                      | None                                     |
	| UCHIJAAAA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge          | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | lorienlegacies | 1.0          | lorienlegacies-1.0 pre release.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 25.20.100.6577' Renderer: 'Intel(R) UHD Graphics 620'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 25.20.100.6577, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
```
